{{- if not .Values.nfs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "langflow.fullname" . }}-data
  labels:
    {{- include "langflow.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.langflow.storage }}
  {{- if .Values.langflow.storageClass }}
  storageClassName: {{ .Values.langflow.storageClass }}
  {{- end }}
{{- end }}
