{{- if not .Values.keycloak.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langflow.fullname" . }}-secret
  labels:
    {{- include "langflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.keycloak.existingSecretKeys.langflowSecretKey }}: {{ .Values.langflow.secretKey | default (randAlphaNum 32) | quote }}
  {{- if .Values.keycloak.enabled }}
  {{ .Values.keycloak.existingSecretKeys.clientSecret }}: {{ .Values.keycloak.clientSecret | quote }}
  {{- end }}
{{- end }}
